---

- hosts: localhost

  connection: local

  gather_facts: False

  tasks:
    - name: Create new Droplet.
      digital_ocean_droplet:
        state: present
        name: mydroplet
        ssh_keys:
          - 31935321 # curl --silent "https://api.digitalocean.com/v2/account/keys" -H "Authorization: Bearer $DO_API_TOKEN" |jq
        size: s-1vcpu-1gb # curl --silent "https://api.digitalocean.com/v2/sizes" -H "Authorization: Bearer $DO_API_TOKEN"
        region: lon1
        image: centos-7-x64 # 49528765 # curl --silent "https://api.digitalocean.com/v2/images?per_page=999" -H "Authorization: Bearer $DO_API_TOKEN" |jq '.images'
        wait_timeout: 500
      register: my_droplet

    - debug:
        msg:
          - "Droplet ID is {{ my_droplet.data.droplet.id }}, Droplet IP is {{ my_droplet.data.ip_address }}"

    - name: Add new host to our inventory.
      add_host:
        name: "{{ my_droplet.data.ip_address }}"
        groups: do
      when: my_droplet.data.droplet is defined
      changed_when: False

- hosts: do
  gather_facts: no
  become: yes

  tasks:
    - name: Wait for port 22 to become available.
      local_action:
        module: wait_for
        port: 22
        host: "{{ inventory_hostname }}"
    - name: Install tcpdump.
      yum:
        name: tcpdump
        state: present
      remote_user: centos
